### ISSUE TITLE
Issues with language settings different from English

### ISSUE THREAD

**Issue by vsht** [tueda/formset#1]
On Linux it seems that formset.py works properly only with `LANG=en_US.UTF-8`. 

This is fine:
```
LANG=en_US.UTF-8
./formset.py
```

```
# formset.py (cpu: 4, mem: 24980017152; total cpu: 4, total mem: 33306689536; 1x4)
compresssize 320000
largesize 6182833001
scratchsize 2060944333
smallextension 1854849900
smallsize 1236566600
sortiosize 7769297
termsinsmall 12365680
threadscratchoutsize 2560000
threadscratchsize 2560000
```

This doesn't work

```
LANG=de_DE.UTF-8
./formset.py
```
Traceback (most recent call last):
  File "./formset.py", line 851, in <module>
    main()
  File "./formset.py", line 636, in main
    total_cpus = SystemInfo.number_of_physical_cores
  File "./formset.py", line 179, in __get__
    return classmethod(self.fget).__get__(None, owner)()
  File "./formset.py", line 212, in number_of_physical_cores
    return int(info["Socket(s)"]) * int(info["Core(s) per socket"])
KeyError: 'Socket(s)'
```

```

**Comment by tueda** [comment]
Yes, this is because it just parses the output of `lscpu` assuming that there is a line starting with `Socket(s):` etc.

**Comment by tueda** [comment]
Does the following patch help in your environment? https://github.com/tueda/formset/commit/140917d3f98b7bdc9eca69c4961e0ec3ff2cf99e

**Comment by vsht** [comment]
Yes, this fixes the issue for me. Thanks!

**Comment by tueda** [comment]
Merged to the master branch. Thanks for your reporting!
