### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by tueda** [tueda/formset#3]
As a single module (`formset.py`), after some refactoring #2, with some documentation and examples in README.

**Comment by tueda** [comment]
This repository uses type annotations, but [PEP 561](https://www.python.org/dev/peps/pep-0561/) doesn't support module-only distributions. The package layout may be changed to 
```
─── formset
    ├── __init__.py
    ├── __main__.py
    ├── formset.py
    └── py.typed
```
in such a way that still `formset.py` can be picked up as a standalone script.

**Comment by tueda** [comment]
It turned out that supporting ancient Python versions in modern developer tools is highly nontrivial, for example:
- https://github.com/python-poetry/poetry/issues/3791
- https://github.com/deadsnakes/issues/issues/128#issuecomment-808922359

We may drop official supports for 2.6, 3.2, 3.3 (and maybe 3.4) in the package information, though we could keep the old code for 2.6, which may work when used as a standalone script.

**Comment by magv** [comment]
As a data point: pySecDec supports Python 2.7 now, but in the next release (where formset.py will be included) we plan to only support Python 3.6+.

**Comment by tueda** [comment]
It turned out that the package name `formset` is not allowed by PyPI, though currently there is no [formset](https://pypi.org/project/formset/):
```
Publishing formset (1.0.0rc1) to PyPI
 - Uploading formset-1.0.0rc1-py2.py3-none-any.whl 100%

  UploadError

  HTTP Error 400: The name 'formset' isn't allowed. See https://pypi.org/help/#project-name for more information.

  at /home/linuxbrew/.linuxbrew/Cellar/poetry/1.1.5/libexec/lib/python3.9/site-packages/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│
    → 216│             raise UploadError(e)
      217│
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None

```

**Comment by magv** [comment]
It was registered by what seems to be a package name squatter. I think if you'll contact the PyPI support, they'll transfer it to you.

**Comment by tueda** [comment]
FYI: some related discussions:
- [Checking if a package name is allowed or forbidden/reserved on PyPI](https://discuss.python.org/t/checking-if-a-package-name-is-allowed-or-forbidden-reserved-on-pypi/8814)
- [Projects automatically deleted from Pypi](https://discuss.python.org/t/projects-automatically-deleted-from-pypi/8710)
- [PEP 541 - Should name squatting be actively discouraged?](https://discuss.python.org/t/pep-541-should-name-squatting-be-actively-discouraged/2407)

Meanwhile, I have started to think about putting some prefix or namespace (related to [How to create a namespace package/project on pypi?](https://discuss.python.org/t/how-to-create-a-namespace-package-project-on-pypi/8723)), maybe `formtools-formset` or `formtools.formset`, because in future I would possibly put more FORM utilities on PyPI, e.g., [formprof](https://github.com/tueda/formprof). I think no one would take `formtools-formset` or `formtools-formprof`.

**Comment by tueda** [comment]
The current version is registered as https://pypi.org/project/formtools-formset/1.0.0rc1.
